[package]
name = "siliconv_core"
version.workspace = true
edition.workspace = true

[lints]
workspace = true

[dependencies]
thiserror = "2.0.17"
tracing = { version = "0.1.44", features = ["log"] }

